let firstname='Naveen';
console.log(firstname);
console.log(typeof firstname);
console.log('------------------------------');
let Companyname='Wondersoft';
console.log(Companyname);
console.log(typeof Companyname);
console.log('--------------------------------');
let mobilenumber=9176306021;
console.log(mobilenumber);
console.log(typeof mobilenumber);
console.log('--------------------------------');
let IsAutomation=true;
console.log(IsAutomation);
console.log(typeof IsAutomation);
console.log('--------------------------------');
let Hasplaywright;
console.log(Hasplaywright);
console.log(typeof Hasplaywright);
console.log('--------------------------------');
